In [45]:
import pandas as pd
import numpy as np

Extract Source: Zillow Rental Price Data
https://www.kaggle.com/paultimothymooney/zillow-house-price-data

In [35]:
# Path
df = "State_MedianRentalPrice_AllHomes.csv"

In [49]:
# Read csv and store into Pandas DF
rental_df = pd.read_csv(df, encoding="ISO-8859-1", index_col=[0])
rental_df

,RegionName,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,...,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,Median Rental Price
0,California,NaN,NaN,2400.0,2400.0,2400.0,2495.0,2500.0,2595.0,2497.0,...,2800,2800.0,2800.0,2800.0,2850,2800.0,2800.0,2800.0,2800.0,2300.0
1,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1575,1595.0,1595.0,1600.0,1595,1590.0,1550.0,1550.0,1550.0,1425.0
2,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3495,3299.0,3295.0,3200.0,3395,3250.0,2950.0,3000.0,3200.0,3000.0
3,Florida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1850,1850.0,1845.0,1800.0,1800,1800.0,1800.0,1795.0,1790.0,1640.0
4,Illinois,1575.0,1500.0,1500.0,1500.0,1500.0,1500.0,1550.0,1520.0,1500.0,...,1600,1600.0,1642.5,1647.0,1650,1625.0,1600.0,1595.0,1590.0,1563.0
5,Pennsylvania,NaN,1400.0,1400.0,1400.0,1437.5,1475.0,1400.0,1450.0,1425.0,...,1400,1400.0,1400.0,1400.0,1400,1375.0,1350.0,1355.0,1350.0,1300.0
6,Ohio,NaN,NaN,NaN,1200.0,1200.0,1200.0,1200.0,1250.0,1100.0,...,1100,1100.0,1100.0,1100.0,1100,1100.0,1100.0,1095.0,1095.0,1000.0
7,Michigan,NaN,1150.0,1200.0,1200.0,1200.0,1250.0,1200.0,1200.0,1200.0,...,1200,1200.0,1200.0,1200.0,1200,1200.0,1200.0,1200.0,1150.0,1000.0
8,Georgia,1037.5,1150.0,1195.0,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0,...,1435,1455.0,1480.0,1475.0,1450,1450.0,1445.0,1445.0,1445.0,1150.0
9,North Carolina,NaN,1000.0,997.0,1025.0,1100.0,1100.0,1100.0,1150.0,1150.0,...,1400,1400.0,1400.0,1400.0,1400,1399.0,1395.0,1395.0,1395.0,1100.0
10,New Jersey,NaN,1650.0,1650.0,1650.0,1675.0,1650.0,1650.0,1600.0,1600.0,...,2000,2100.0,2100.0,2000.0,2000,2000.0,2000.0,1975.0,1975.0,1850.0
11,Virginia,NaN,1350.0,1300.0,1350.0,1400.0,1450.0,1500.0,1450.0,1395.0,...,1700,1770.0,1800.0,1795.0,1750,1745.0,1700.0,1695.0,1660.0,1550.0
12,Washington,1200.0,1200.0,1350.0,1350.0,1395.0,1400.0,1495.0,1550.0,1500.0,...,2000,2100.0,2100.0,2145.0,2100,2000.0,1995.0,1995.0,1995.0,1500.0
13,Massachusetts,NaN,1530.0,1575.0,1700.0,1575.0,1800.0,1562.5,1600.0,1650.0,...,2700,2700.0,2700.0,2695.0,2595,2500.0,2500.0,2500.0,2500.0,2397.0
14,Indiana,NaN,1200.0,1200.0,1250.0,1250.0,1250.0,1250.0,1300.0,1150.0,...,1100,1100.0,1100.0,1100.0,1145,1110.0,1100.0,1095.0,1050.0,995.0
15,Arizona,NaN,NaN,1400.0,1377.5,1300.0,1299.0,1250.0,1295.0,1250.0,...,1500,1545.0,1550.0,1550.0,1550,1545.0,1495.0,1499.0,1495.0,1232.5
16,Tennessee,NaN,NaN,1150.0,1200.0,1300.0,1350.0,1298.0,1250.0,1250.0,...,1350,1395.0,1395.0,1400.0,1395,1375.0,1350.0,1350.0,1375.0,1150.0
17,Missouri,NaN,1175.0,1250.0,1100.0,1100.0,1100.0,1072.5,1150.0,1050.0,...,1000,1000.0,1050.0,1050.0,1050,1050.0,1045.0,1025.0,1042.5,950.0
18,Maryland,NaN,1600.0,1600.0,1600.0,1650.0,1700.0,1700.0,1700.0,1695.0,...,1700,1750.0,1775.0,1775.0,1750,1750.0,1700.0,1712.5,1700.0,1695.0
19,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1250,1250.0,1215.0,1200.0,1200,1200.0,1200.0,1200.0,1200.0,1150.0
20,Minnesota,NaN,NaN,NaN,1535.0,1400.0,1537.5,1697.5,1650.0,1485.0,...,1600,1600.0,1600.0,1600.0,1600,1600.0,1600.0,1600.0,1600.0,1400.0
21,Colorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1975,1995.0,1995.0,1975.0,1995,2000.0,2000.0,1995.0,2000.0,1650.0
22,Alabama,NaN,NaN,NaN,NaN,1095.0,1100.0,1100.0,1050.0,995.0,...,1095,1095.0,1095.0,1065.0,1050,1045.0,1050.0,1050.0,1050.0,975.0
23,South Carolina,NaN,NaN,1100.0,1200.0,1200.0,1200.0,1192.5,1195.0,1150.0,...,1375,1400.0,1400.0,1400.0,1395,1350.0,1342.5,1350.0,1350.0,1200.0
24,Louisiana,NaN,1200.0,1200.0,1200.0,1250.0,1250.0,1300.0,1225.0,1122.5,...,1295,1275.0,1250.0,1250.0,1200,1200.0,1200.0,1200.0,1200.0,1200.0
25,Kentucky,NaN,NaN,NaN,NaN,1200.0,1195.0,1200.0,1050.0,1050.0,...,1150,1195.0,1175.0,1150.0,1125,1150.0,1145.0,1145.0,1100.0,995.0
26,Oregon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750,1795.0,1800.0,1850.0,1850,1895.0,1850.0,1850.0,1800.0,1470.0
27,Oklahoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1095,1095.0,1050.0,1095.0,1050,1050.0,1000.0,1000.0,1000.0,1000.0
28,Connecticut,NaN,1700.0,1800.0,1900.0,1850.0,2000.0,1875.0,1800.0,1700.0,...,1800,1850.0,1850.0,1850.0,1800,1800.0,1800.0,1800.0,1800.0,1750.0
29,Iowa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1100.0,1100.0,1100.0,1100,1095.0,1100.0,1100.0,1075.0,1050.0
30,Mississippi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1200,1195.0,1160.0,1150.0,1150,1122.5,1167.5,1175.0,1150.0,1000.0
31,Arkansas,NaN,900.0,900.0,850.0,850.0,900.0,897.5,895.0,850.0,...,1100,1100.0,1100.0,1100.0,1100,1050.0,1050.0,1075.0,1050.0,995.0
32,Kansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1100.0,1100.0,1092.5,1050,1000.0,1000.0,1047.5,1025.0,1050.0
33,Utah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500,1525.0,1500.0,1550.0,1591,1575.0,1525.0,1525.0,1500.0,1250.0
34,Nevada,NaN,NaN,1275.0,1250.0,1250.0,1250.0,1212.5,1250.0,1250.0,...,1550,1550.0,1562.0,1580.0,1565,1550.0,1550.0,1550.0,1540.0,1250.0
35,New Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.0,...,1250,1250.0,1250.0,1250.0,1250,1250.0,1250.0,1250.0,1250.0,1150.0
36,West Virginia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1000,1050.0,1000.0,1000.0,1000,975.0,990.0,1000.0,975.0,1000.0
37,Nebraska,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1300,1295.0,1295.0,1295.0,1250,1200.0,1200.0,1200.0,1195.0,1225.0
38,Idaho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1350,1395.0,1400.0,1400.0,1450,1425.0,1400.0,1399.0,1400.0,995.0
39,Hawaii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2350,2400.0,2400.0,2400.0,2375,2400.0,2350.0,2350.0,2300.0,2300.0
40,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750,1800.0,1800.0,1800.0,1800,1700.0,1700.0,1750.0,1750.0,1637.5
41,New Hampshire,NaN,1237.5,1225.0,1300.0,1395.0,1350.0,1500.0,1500.0,1495.0,...,1750,1800.0,1800.0,1825.0,1800,1795.0,1750.0,1700.0,1700.0,1495.0
42,Rhode Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2100,2100.0,2100.0,2000.0,2000,2000.0,2000.0,2000.0,2000.0,1750.0
43,Montana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1300,1300.0,1350.0,1350.0,1400,1350.0,1350.0,1300.0,1295.0,1097.5
44,Delaware,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1390,1412.5,1450.0,1445.0,1425,1450.0,1450.0,1400.0,1400.0,1300.0
45,South Dakota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1135.0,1150.0,1150.0,1150,1125.0,1137.5,1150.0,1175.0,1100.0
46,Alaska,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1695,1682.5,1650.0,1675.0,1695,1650.0,1650.0,1650.0,1600.0,1600.0
47,North Dakota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1350,1300.0,1295.0,1250.0,1300,1300.0,1295.0,1295.0,1250.0,1295.0
48,District of Columbia,NaN,2275.0,1972.5,1999.0,2000.0,2125.0,2300.0,2200.0,2180.0,...,2650,2700.0,2750.0,2730.0,2700,2700.0,2700.0,2700.0,2730.0,2500.0
49,Wyoming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1125.0,1185.0,1150.0,1250,1200.0,1150.0,1195.0,1150.0,1100.0
50,Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500,1600.0,1800.0,1625.0,1650,1650.0,1800.0,1650.0,1700.0,1500.0

Transform

In [50]:
# Rename Region Name column to State
med_rental_df = rental_df.rename(columns={"RegionName": "State",})
med_rental_df

,State,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,...,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,Median Rental Price
0,California,NaN,NaN,2400.0,2400.0,2400.0,2495.0,2500.0,2595.0,2497.0,...,2800,2800.0,2800.0,2800.0,2850,2800.0,2800.0,2800.0,2800.0,2300.0
1,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1575,1595.0,1595.0,1600.0,1595,1590.0,1550.0,1550.0,1550.0,1425.0
2,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3495,3299.0,3295.0,3200.0,3395,3250.0,2950.0,3000.0,3200.0,3000.0
3,Florida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1850,1850.0,1845.0,1800.0,1800,1800.0,1800.0,1795.0,1790.0,1640.0
4,Illinois,1575.0,1500.0,1500.0,1500.0,1500.0,1500.0,1550.0,1520.0,1500.0,...,1600,1600.0,1642.5,1647.0,1650,1625.0,1600.0,1595.0,1590.0,1563.0
5,Pennsylvania,NaN,1400.0,1400.0,1400.0,1437.5,1475.0,1400.0,1450.0,1425.0,...,1400,1400.0,1400.0,1400.0,1400,1375.0,1350.0,1355.0,1350.0,1300.0
6,Ohio,NaN,NaN,NaN,1200.0,1200.0,1200.0,1200.0,1250.0,1100.0,...,1100,1100.0,1100.0,1100.0,1100,1100.0,1100.0,1095.0,1095.0,1000.0
7,Michigan,NaN,1150.0,1200.0,1200.0,1200.0,1250.0,1200.0,1200.0,1200.0,...,1200,1200.0,1200.0,1200.0,1200,1200.0,1200.0,1200.0,1150.0,1000.0
8,Georgia,1037.5,1150.0,1195.0,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0,...,1435,1455.0,1480.0,1475.0,1450,1450.0,1445.0,1445.0,1445.0,1150.0
9,North Carolina,NaN,1000.0,997.0,1025.0,1100.0,1100.0,1100.0,1150.0,1150.0,...,1400,1400.0,1400.0,1400.0,1400,1399.0,1395.0,1395.0,1395.0,1100.0
10,New Jersey,NaN,1650.0,1650.0,1650.0,1675.0,1650.0,1650.0,1600.0,1600.0,...,2000,2100.0,2100.0,2000.0,2000,2000.0,2000.0,1975.0,1975.0,1850.0
11,Virginia,NaN,1350.0,1300.0,1350.0,1400.0,1450.0,1500.0,1450.0,1395.0,...,1700,1770.0,1800.0,1795.0,1750,1745.0,1700.0,1695.0,1660.0,1550.0
12,Washington,1200.0,1200.0,1350.0,1350.0,1395.0,1400.0,1495.0,1550.0,1500.0,...,2000,2100.0,2100.0,2145.0,2100,2000.0,1995.0,1995.0,1995.0,1500.0
13,Massachusetts,NaN,1530.0,1575.0,1700.0,1575.0,1800.0,1562.5,1600.0,1650.0,...,2700,2700.0,2700.0,2695.0,2595,2500.0,2500.0,2500.0,2500.0,2397.0
14,Indiana,NaN,1200.0,1200.0,1250.0,1250.0,1250.0,1250.0,1300.0,1150.0,...,1100,1100.0,1100.0,1100.0,1145,1110.0,1100.0,1095.0,1050.0,995.0
15,Arizona,NaN,NaN,1400.0,1377.5,1300.0,1299.0,1250.0,1295.0,1250.0,...,1500,1545.0,1550.0,1550.0,1550,1545.0,1495.0,1499.0,1495.0,1232.5
16,Tennessee,NaN,NaN,1150.0,1200.0,1300.0,1350.0,1298.0,1250.0,1250.0,...,1350,1395.0,1395.0,1400.0,1395,1375.0,1350.0,1350.0,1375.0,1150.0
17,Missouri,NaN,1175.0,1250.0,1100.0,1100.0,1100.0,1072.5,1150.0,1050.0,...,1000,1000.0,1050.0,1050.0,1050,1050.0,1045.0,1025.0,1042.5,950.0
18,Maryland,NaN,1600.0,1600.0,1600.0,1650.0,1700.0,1700.0,1700.0,1695.0,...,1700,1750.0,1775.0,1775.0,1750,1750.0,1700.0,1712.5,1700.0,1695.0
19,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1250,1250.0,1215.0,1200.0,1200,1200.0,1200.0,1200.0,1200.0,1150.0
20,Minnesota,NaN,NaN,NaN,1535.0,1400.0,1537.5,1697.5,1650.0,1485.0,...,1600,1600.0,1600.0,1600.0,1600,1600.0,1600.0,1600.0,1600.0,1400.0
21,Colorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1975,1995.0,1995.0,1975.0,1995,2000.0,2000.0,1995.0,2000.0,1650.0
22,Alabama,NaN,NaN,NaN,NaN,1095.0,1100.0,1100.0,1050.0,995.0,...,1095,1095.0,1095.0,1065.0,1050,1045.0,1050.0,1050.0,1050.0,975.0
23,South Carolina,NaN,NaN,1100.0,1200.0,1200.0,1200.0,1192.5,1195.0,1150.0,...,1375,1400.0,1400.0,1400.0,1395,1350.0,1342.5,1350.0,1350.0,1200.0
24,Louisiana,NaN,1200.0,1200.0,1200.0,1250.0,1250.0,1300.0,1225.0,1122.5,...,1295,1275.0,1250.0,1250.0,1200,1200.0,1200.0,1200.0,1200.0,1200.0
25,Kentucky,NaN,NaN,NaN,NaN,1200.0,1195.0,1200.0,1050.0,1050.0,...,1150,1195.0,1175.0,1150.0,1125,1150.0,1145.0,1145.0,1100.0,995.0
26,Oregon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750,1795.0,1800.0,1850.0,1850,1895.0,1850.0,1850.0,1800.0,1470.0
27,Oklahoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1095,1095.0,1050.0,1095.0,1050,1050.0,1000.0,1000.0,1000.0,1000.0
28,Connecticut,NaN,1700.0,1800.0,1900.0,1850.0,2000.0,1875.0,1800.0,1700.0,...,1800,1850.0,1850.0,1850.0,1800,1800.0,1800.0,1800.0,1800.0,1750.0
29,Iowa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1100.0,1100.0,1100.0,1100,1095.0,1100.0,1100.0,1075.0,1050.0
30,Mississippi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1200,1195.0,1160.0,1150.0,1150,1122.5,1167.5,1175.0,1150.0,1000.0
31,Arkansas,NaN,900.0,900.0,850.0,850.0,900.0,897.5,895.0,850.0,...,1100,1100.0,1100.0,1100.0,1100,1050.0,1050.0,1075.0,1050.0,995.0
32,Kansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1100.0,1100.0,1092.5,1050,1000.0,1000.0,1047.5,1025.0,1050.0
33,Utah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500,1525.0,1500.0,1550.0,1591,1575.0,1525.0,1525.0,1500.0,1250.0
34,Nevada,NaN,NaN,1275.0,1250.0,1250.0,1250.0,1212.5,1250.0,1250.0,...,1550,1550.0,1562.0,1580.0,1565,1550.0,1550.0,1550.0,1540.0,1250.0
35,New Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.0,...,1250,1250.0,1250.0,1250.0,1250,1250.0,1250.0,1250.0,1250.0,1150.0
36,West Virginia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1000,1050.0,1000.0,1000.0,1000,975.0,990.0,1000.0,975.0,1000.0
37,Nebraska,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1300,1295.0,1295.0,1295.0,1250,1200.0,1200.0,1200.0,1195.0,1225.0
38,Idaho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1350,1395.0,1400.0,1400.0,1450,1425.0,1400.0,1399.0,1400.0,995.0
39,Hawaii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2350,2400.0,2400.0,2400.0,2375,2400.0,2350.0,2350.0,2300.0,2300.0
40,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750,1800.0,1800.0,1800.0,1800,1700.0,1700.0,1750.0,1750.0,1637.5
41,New Hampshire,NaN,1237.5,1225.0,1300.0,1395.0,1350.0,1500.0,1500.0,1495.0,...,1750,1800.0,1800.0,1825.0,1800,1795.0,1750.0,1700.0,1700.0,1495.0
42,Rhode Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2100,2100.0,2100.0,2000.0,2000,2000.0,2000.0,2000.0,2000.0,1750.0
43,Montana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1300,1300.0,1350.0,1350.0,1400,1350.0,1350.0,1300.0,1295.0,1097.5
44,Delaware,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1390,1412.5,1450.0,1445.0,1425,1450.0,1450.0,1400.0,1400.0,1300.0
45,South Dakota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1135.0,1150.0,1150.0,1150,1125.0,1137.5,1150.0,1175.0,1100.0
46,Alaska,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1695,1682.5,1650.0,1675.0,1695,1650.0,1650.0,1650.0,1600.0,1600.0
47,North Dakota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1350,1300.0,1295.0,1250.0,1300,1300.0,1295.0,1295.0,1250.0,1295.0
48,District of Columbia,NaN,2275.0,1972.5,1999.0,2000.0,2125.0,2300.0,2200.0,2180.0,...,2650,2700.0,2750.0,2730.0,2700,2700.0,2700.0,2700.0,2730.0,2500.0
49,Wyoming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1125.0,1185.0,1150.0,1250,1200.0,1150.0,1195.0,1150.0,1100.0
50,Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500,1600.0,1800.0,1625.0,1650,1650.0,1800.0,1650.0,1700.0,1500.0

In [54]:
#Drop NAN values
clean_rental_df = med_rental_df.dropna(how='any')
clean_rental_df

,State,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,...,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,Median Rental Price
4,Illinois,1575.0,1500.0,1500.0,1500.0,1500.0,1500.0,1550.0,1520.0,1500.0,...,1600,1600.0,1642.5,1647.0,1650,1625.0,1600.0,1595.0,1590.0,1563.0
8,Georgia,1037.5,1150.0,1195.0,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0,...,1435,1455.0,1480.0,1475.0,1450,1450.0,1445.0,1445.0,1445.0,1150.0
12,Washington,1200.0,1200.0,1350.0,1350.0,1395.0,1400.0,1495.0,1550.0,1500.0,...,2000,2100.0,2100.0,2145.0,2100,2000.0,1995.0,1995.0,1995.0,1500.0

In [71]:
clean_rental_df = clean_rental_df[['State', 'Median Rental Price']]
clean_rental_df

         State  Median Rental Price
4     Illinois               1563.0
8      Georgia               1150.0
12  Washington               1500.0